# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: rainZhao
email: 695099976@qq.com
description: 将来的你一定会感激那个现在奋斗的你！
baseurl: "/zblog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: none
github_username:  rainzhao

# Build settings
markdown: kramdown

Regeneration: -w
